apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-finder-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-finder
  template:
    metadata:
      labels:
        app: github-finder
    spec:
      containers:
        - name: github-finder-container
          image: ishwardr/github-finder:v1
          ports:
            - containerPort: 80
